### ISSUE TITLE
[Question] CONC(TEMP,SALT) variable communication

### ISSUE THREAD

**Issue by kihangyoun** [fearghalodonncha/EFDC-MPI#1]
Dear Fearghal O'Donncha,

I'm enjoying your work very much because I'm working on a parallel EFDC at work.
I have a question for you.

In CALTRAN subroutine, TEMP, SALT, etc. are calculated by converting CON. 
And CON variable use the index of LW, LS, LN, etc. 
In your program TEMP, SALT, etc. are seen as communicating in HDMT.
Is there no problem? I think that it is need to communicate CON when new CON is calculated.

Currently, I am trying to reduce MPI communication as it takes a lot of time,
Therefore I am asking because your code does not have a lot of MPI communication.

Thank you.

https://github.com/fearghalodonncha/EFDC-MPI/blob/4a2d8155a4fa0f78f670eb325b77f63aa4acdf01/Src/CALTRAN.f#L185-L186

**Comment by fearghalodonncha** [comment]
Hello,

Thanks for your interest! Yes, you are correct that since TEMP, SALT, etc. have spatial dependency they need to be MPI communicated across domains.

This is done at the end of each [timestep as part of the MPI synchronization ](https://github.com/fearghalodonncha/EFDC-MPI/blob/5a9ca414a42413aa11cbd35f9f0123113caf6228/Src/HDMT2T.F#L1595). 

The reason that it is done here instead of in CALTRAN acting individually on each `CON` is to reduce the number of times that MPI domains must wait on their neighbours to communicate data. This is particulalry relevant in ocean type simulations which are often imbalanced due to the complex mix of land (low computational expense) water (high computational expense) cells often leading to load imbalance.

Thanks for your interest in the code. Feel free to drop any questions or suggest any changes.

**Comment by kihangyoun** [comment]
Hi,

Reducing the amount of communication is an important issue for me, 
so I'll look at your codes a little more and ask you.

Thank you for your reply!
